apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.mongoLabel }}
  labels:
    app: {{ .Values.mongo.mongoLabel }}
spec:
  replicas: {{ .Values.mongo.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mongo.mongoLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.mongoLabel }}
    spec:
      containers:
      - name: {{ .Values.mongo.mongoLabel }}
        image: {{ .Values.mongo.imageName }}
        imagePullPolicy: {{ .Values.mongo.pullPolicy }}
        ports:
        - containerPort: {{ .Values.mongo.containerPort }}
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
